---
# tasks file for ansible-role-virtual-interface

- include_vars: "{{ ansible_os_family }}.yml"

- include: "configure-{{ ansible_os_family }}.yml"

- include: "destroy-{{ ansible_os_family }}.yml"
